# Site settings
title: Azrrrrr
name: Azr的博客 | Blog
SEOTitle: Azr的博客 | Blog
header-img: img/post-bg-desk.jpg
email: azr8023@gmail.com
description: "Azr的博客是一个分享技术教程，共享资源，前端开发者交流的个人独立博客。"
keyword: "Blog, Azrrrrr,Azr的博客,博客,个人博客,前端开发,前端博客,源码分享,前端课堂,前端学习,编程基础"
url: "https://amor9.cn/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/azrrrrr/azrrrrr.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "感谢生活  有剥夺  也有馈赠。"
sidebar-avatar: https://ws2.sinaimg.cn/large/006tNbRwly1fxej6om0zxj30jg0jgq3o.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     SunnyAmor
zhihu_username:     azr7
github_username:    azrrrrr
# facebook_username:  Amor_dr7
jianshu_username:   93d333ac3afd
# twitter_username:   Amor_dr7



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: azrrrrr

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 859e47f4d4c09b159b29                            #生成的clientID
  clientSecret: 9eb9c9aff4594daf2b3733804284a06832e8c3fa    #生成的clientSecret
  repo: azrrrrr.github.io    #仓库名称
  owner: azrrrrr    #github用户名
  admin: azrrrrr
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 84f8c229e6242111dd9ad43d36c8075f

# Google Analytics
ga_track_id: 'UA-131190596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto                          # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends

friends: [
    {
        title: "阮一峰",
        href: "http://www.ruanyifeng.com/blog/"
    },
    {
        title: "张鑫旭",
        href: "https://www.zhangxinxu.com/"
    },
    {
        title: "朴灵",
        href: "http://html5ify.com/"
    },
    {
        title: "廖雪峰",
        href: "https://www.liaoxuefeng.com/"
    },
    {
        title: "颜海镜",
        href: "https://yanhaijing.com/"
    },
#     {
#         title: "AmorR",
#         href: "https://www.cnblogs.com/AmorR/"
#     },
    {
        title: "大漠穷秋",
        href: "http://www.ngfans.net/"
    },
    {
        title: "游魂",
        href: "https://www.iyouhun.com/"
    },
    {
        title: "奇淼",
        href: "http://www.henrongyi.top/"
    },
    {
        title: "小翼",
        href: "https://www.my-fe.pub/"
    },
    {
        title: "前端大爆炸",
        href: "https://alili.tech/"
    },
    {
        title: "sumorfly",
        href: "http://sumorfly.github.io"
    },
    {
        title: "jartto",
        href: "http://jartto.wang/"
    }
]


# theme: jekyll-theme-midnight
